### ISSUE TITLE
Instructions for Mac

### ISSUE THREAD

**Issue by jesscs** [fogies/web-jekyll-base#42]
For Macs:

Installing Node.js, Python, and Ruby

Install Homebrew (source: http://brew.sh/):
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

Install Node:
    brew install node

Install Python3:
    brew install python3

Install Ruby (source: https://gorails.com/setup/osx/10.11-el-capitan):
    brew install rbenv ruby-build 
    echo 'if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi' >> ~/.bash_profile
    source ~/.bash_profile
    rbenv install 2.2.3
    rbenv global 2.2.3

Install Pip (source: https://pip.pypa.io/en/stable/installing/):
    Download and run get-pip.py: https://bootstrap.pypa.io/get-pip.py 

Creating a Virtual Environment and Installing Dependencies (source: http://docs.python-guide.org/en/latest/dev/virtualenvs/)
    Install virtualenv:
        pip install virtualenv
    Create a virtual environment:
        cd [working directory of our project (e.g., c:\devel\web-cse510-wi16)]
        virtualenv -p python3 env35
        source env35/bin/activate
        pip install -r requirements3.txt
    Get the rest of the dependencies:
        invoke update_dependencies

Build and Serve the Site:
    If not active, activate the virtual environment:
        source env35/bin/activate 
    Build the site:
        invoke build_test
    Build and serve on localhost:4000:
        invoke serve_test 
    Deactivate the virtual environment when finished: 
        deactivate

**Comment by lrpina** [comment]
In `pip install virtualenv` I had to do `pip3 install virtualenv`

**Comment by jayfo** [comment]
Added to invoke-base.  Will get updated into this project.
